# render.yaml — Blueprint deploy: Web (FastAPI) + Managed Postgres
services:
  - type: web
    name: journal-api
    env: python
    plan: free
    region: oregon
    autoDeploy: true

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: >
      bash -lc '
      # Render supplies DATABASE_URL as postgres:// or postgresql:// (sync).
      # Convert to async for SQLAlchemy’s async engine at runtime.
      export DATABASE_URL=$(echo "$DATABASE_URL" | sed -E "s/^postgres(ql)?:\/\//postgresql+asyncpg:\/\//");
      # Run the app; Render sets $PORT
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
      '

    envVars:
      # Link the managed DB; Render injects the connection string
      - key: DATABASE_URL
        fromDatabase:
          name: journal-db
          property: connectionString

      # App env knobs
      - key: APP_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PROMETHEUS_ENABLED
        value: true
      # - key: SENTRY_DSN
      #   value: <your-dsn>  # leave unset to disable Sentry

    healthCheckPath: /healthz

    # Run DB migrations *after* each deploy
    postdeployCommand: alembic upgrade head

    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=63072000; includeSubDomains; preload
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: DENY

databases:
  - name: journal-db
    plan: free
    region: oregon
