# .github/workflows/ci.yml
name: CI — Tests & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: journal_db_test
        # Healthcheck so the container re-tries until it's actually ready
        options: >-
          --health-cmd="pg_isready -U postgres -d journal_db_test || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    env:
      # IMPORTANT: sync driver for Alembic in CI (no +asyncpg)
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/journal_db_test
      PYTHONPATH: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Install Postgres client (psql/pg_isready)
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      # Extra defensive wait (even though the service healthcheck exists)
      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for postgres service…"
          until pg_isready -h postgres -U postgres -d journal_db_test; do
            sleep 1
          done
          echo "Postgres is ready."

      - name: Smoke check DB connectivity (SELECT version)
        env:
          PGPASSWORD: postgres
        run: |
          psql -h postgres -U postgres -d journal_db_test -c "SELECT version();"

      - name: Show services & health (debug)
        if: always()
        run: |
          docker ps -a
          (echo > /dev/tcp/postgres/5432) >/dev/null 2>&1 && echo "5432 is open" || echo "5432 not open"

      - name: Print Postgres logs (debug)
        if: always()
        run: |
          echo "----- postgres container logs -----"
          docker logs ${{ job.services.postgres.id }} || true
          echo "-----------------------------------"

      - name: Debug DB URL (settings vs env)
        run: |
          echo "DATABASE_URL (env): ${DATABASE_URL}"
          python - <<'PY'
          from app.core.config import settings
          print("settings.database_url:", settings.database_url)
          print("settings.sync_database_url:", settings.sync_database_url)
          PY

      - name: Run Alembic migrations
        run: alembic upgrade head

      - name: Run tests with coverage
        run: pytest --cov=app --cov-report=xml --cov-fail-under=90

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
