# .github/workflows/trivy.yml
name: Security — Trivy FS Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # weekly scan (Sun 06:00 UTC)
    - cron: "0 6 * * 0"

permissions:
  contents: read
  actions: read
  security-events: write  # required for SARIF upload

jobs:
  trivy-fs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Run Trivy via Docker to avoid setup-trivy env quirks
      - name: Run Trivy filesystem scan (Docker)
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/src" \
            -w /src \
            aquasec/trivy:0.56.1 fs \
              --scanners vuln,misconfig,secret,license \
              --severity CRITICAL,HIGH \
              --ignore-unfixed \
              --format sarif \
              --timeout 5m \
              --output trivy-results.sarif \
              --skip-dirs ".git,.venv,venv,node_modules,migrations/__pycache__,app/**/__pycache__" \
              .

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Upload raw Trivy report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.sarif
