name: Uptime - API Health

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Warm up (tolerate cold start)
        run: |
          set -euo pipefail
          curl -s -o /dev/null --max-time 20 "https://journal-starter.onrender.com/docs" || true

      - name: Check /healthz (retry up to ~2 min)
        run: |
          set -euo pipefail
          URL="https://journal-starter.onrender.com/healthz"
          OUT="$(curl -fsS -o /tmp/resp -w "%{http_code} %{time_total}" \
                --max-time 20 --retry 6 --retry-delay 10 --retry-all-errors "$URL" || true)"
          CODE="$(echo "$OUT" | awk '{print $1}')"
          LATENCY="$(echo "$OUT" | awk '{print $2}')"
          echo "HTTP_CODE=$CODE LATENCY=${LATENCY:-unknown}s"
          if [ "$CODE" != "200" ]; then
            echo "Healthcheck failed ❌"
            echo "Last response (truncated):"
            head -c 300 /tmp/resp || true
            exit 1
          fi
          echo "OK ✅"

      - name: Check /metrics when enabled (non-blocking)
        if: always()
        run: |
          METRICS_URL="https://journal-starter.onrender.com/metrics"
          CODE="$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "$METRICS_URL" || true)"
          echo "METRICS_HTTP_CODE=$CODE"
          test "$CODE" = "200" && echo "Metrics OK ✅" || echo "Metrics not available (OK if disabled)"
      - name: Slack alert on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"Uptime check failed for *journal-starter* :x: — investigate /healthz.\"}" \
            "$SLACK_WEBHOOK_URL"

      - name: Send test Slack message
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Manual test of Slack alerts for *journal-starter* :white_check_mark:"}' \
            "$SLACK_WEBHOOK_URL"
